security.jwt.jwk.private-key-path=classpath:jwk.json
management.endpoints.web.exposure.include=*
management.httpexchanges.recording.enabled=true
logging.level.org.springframework.web=DEBUG
security.jwt.secure-cookie=false
