spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
#security.jwt.jwk.public-key-path=classpath:jwk.pub.json
security.jwt.jwk.private-key-path=classpath:jwk.json
spring.jpa.hibernate.ddl-auto=create
management.endpoints.jmx.exposure.include=*
management.httpexchanges.recording.enabled=true
logging.level.org.springframework.web=DEBUG
