security.jwt.jwk.public-key-set-path=classpath:jwks.public.json
security.jwt.jwk.private-key-set-path=classpath:jwks.private.json
security.jwt.jwk.signing-alg=EdDSA
security.jwt.jwk.signing-kid=demo-key
management.endpoints.web.exposure.include=*
management.httpexchanges.recording.enabled=true
logging.level.org.springframework.web=DEBUG
security.jwt.secure-cookie=false
