###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "user": {
    "email": "demo@example.com"
  },
  "password": "password123"
}

> {%
    client.global.set("auth_token", response.body.sessionToken);
%}

###
GET http://localhost:8080/auth/info
Authorization: Bearer {{auth_token}}

###
POST http://localhost:8080/auth/refresh

###
POST http://localhost:8080/auth/logout
