style:
  FunctionOnlyReturningConstant:
    ignoreAnnotated:
      - org.springframework.web.bind.annotation.*Mapping
  MagicNumber:
    active: true
    ignoreAnnotated:
      - 'org.springframework.boot.context.properties.ConfigurationProperties'
  ReturnCount:
    excludeGuardClauses: true
